"""Belonging operations and contact network
Revision ID: 0003_belonging_contacts
Revises: 0002_people_org_contacts
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0003_belonging_contacts"; down_revision="0002_people_org_contacts"; branch_labels=None; depends_on=None

def uid(): return postgresql.UUID(as_uuid=True)
def upgrade():
    op.create_table("contacts",sa.Column("id",uid(),primary_key=True),sa.Column("owner_person_id",uid(),sa.ForeignKey("people.id")),sa.Column("linked_person_id",uid(),sa.ForeignKey("people.id")),sa.Column("organization_id",uid(),sa.ForeignKey("organizations.id")),sa.Column("session_id",uid(),sa.ForeignKey("sessions.id")),sa.Column("scope",sa.String(30),nullable=False),sa.Column("first_name",sa.String(120),nullable=False),sa.Column("last_name",sa.String(120),nullable=False),sa.Column("title",sa.String(160)),sa.Column("company",sa.String(200)),sa.Column("email",sa.String(320)),sa.Column("phone",sa.String(40)),sa.Column("notes",sa.Text()),sa.Column("connection_context",sa.String(300)),sa.Column("future_outreach_consent",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_by_person_id",uid(),sa.ForeignKey("people.id")),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index("ix_contacts_owner_person_id","contacts",["owner_person_id"]);op.create_index("ix_contacts_organization_id","contacts",["organization_id"]);op.create_index("ix_contacts_session_id","contacts",["session_id"]);op.create_index("ix_contacts_scope","contacts",["scope"])
    op.create_table("community_partners",sa.Column("id",uid(),primary_key=True),sa.Column("organization_id",uid(),sa.ForeignKey("organizations.id"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("description",sa.Text()),sa.Column("email",sa.String(320)),sa.Column("phone",sa.String(40)),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("belonging_challenges",sa.Column("id",uid(),primary_key=True),sa.Column("organization_id",uid(),sa.ForeignKey("organizations.id"),nullable=False),sa.Column("session_id",uid(),sa.ForeignKey("sessions.id")),sa.Column("community_partner_id",uid(),sa.ForeignKey("community_partners.id")),sa.Column("name",sa.String(200),nullable=False),sa.Column("description",sa.Text()),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("starts_at",sa.DateTime(timezone=True)),sa.Column("ends_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table("collection_categories",sa.Column("id",uid(),primary_key=True),sa.Column("challenge_id",uid(),sa.ForeignKey("belonging_challenges.id"),nullable=False),sa.Column("key",sa.String(80),nullable=False),sa.Column("name",sa.String(160),nullable=False),sa.Column("unit",sa.String(40),nullable=False,server_default="items"),sa.Column("goal_quantity",sa.String(40)),sa.Column("monetary_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("monetary_goal",sa.String(40)),sa.Column("acceptance_rules",sa.Text()),sa.Column("priority",sa.String(20),nullable=False,server_default="normal"),sa.Column("is_active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("challenge_teams",sa.Column("id",uid(),primary_key=True),sa.Column("challenge_id",uid(),sa.ForeignKey("belonging_challenges.id"),nullable=False),sa.Column("name",sa.String(120),nullable=False))
    op.create_table("challenge_team_members",sa.Column("id",uid(),primary_key=True),sa.Column("team_id",uid(),sa.ForeignKey("challenge_teams.id"),nullable=False),sa.Column("person_id",uid(),sa.ForeignKey("people.id"),nullable=False),sa.Column("role_key",sa.String(80),nullable=False),sa.UniqueConstraint("team_id","person_id"))
    op.create_table("collection_transactions",sa.Column("id",uid(),primary_key=True),sa.Column("challenge_id",uid(),sa.ForeignKey("belonging_challenges.id"),nullable=False),sa.Column("team_id",uid(),sa.ForeignKey("challenge_teams.id")),sa.Column("category_id",uid(),sa.ForeignKey("collection_categories.id")),sa.Column("contribution_type",sa.String(20),nullable=False),sa.Column("subcategory",sa.String(120)),sa.Column("quantity",sa.String(40)),sa.Column("amount",sa.String(40)),sa.Column("donor_name",sa.String(200)),sa.Column("designation",sa.String(200)),sa.Column("qc_status",sa.String(30),nullable=False,server_default="pending"),sa.Column("notes",sa.Text()),sa.Column("entered_by_person_id",uid(),sa.ForeignKey("people.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table("outreach_activities",sa.Column("id",uid(),primary_key=True),sa.Column("challenge_id",uid(),sa.ForeignKey("belonging_challenges.id"),nullable=False),sa.Column("team_id",uid(),sa.ForeignKey("challenge_teams.id")),sa.Column("activity_type",sa.String(80),nullable=False),sa.Column("contact_name",sa.String(200)),sa.Column("organization_name",sa.String(200)),sa.Column("outcome",sa.String(300)),sa.Column("notes",sa.Text()),sa.Column("entered_by_person_id",uid(),sa.ForeignKey("people.id"),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),server_default=sa.func.now()))

def downgrade():
    for t in ["outreach_activities","collection_transactions","challenge_team_members","challenge_teams","collection_categories","belonging_challenges","community_partners","contacts"]: op.drop_table(t)
