"""templates sessions teams consent
Revision ID: 0004_templates_sessions_consent
Revises: 0003_belonging_contacts
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0004_templates_sessions_consent'; down_revision='0003_belonging_contacts'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('program_templates',
      sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('simulation_type_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('simulation_types.id'),nullable=False),
      sa.Column('name',sa.String(200),nullable=False),sa.Column('description',sa.Text()),sa.Column('default_role_key',sa.String(80),server_default='team_member'),
      sa.Column('role_assignment_mode',sa.String(30),nullable=False,server_default='manual_default'),sa.Column('max_teams',sa.Integer(),nullable=False,server_default='4'),
      sa.Column('status',sa.String(30),nullable=False,server_default='draft'),sa.Column('version',sa.Integer(),nullable=False,server_default='1'),sa.Column('archived_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.add_column('sessions',sa.Column('template_id',postgresql.UUID(as_uuid=True),nullable=True)); op.create_foreign_key('fk_sessions_template','sessions','program_templates',['template_id'],['id']); op.create_index('ix_sessions_template_id','sessions',['template_id'])
    op.add_column('sessions',sa.Column('status',sa.String(30),nullable=False,server_default='draft')); op.add_column('sessions',sa.Column('team_count',sa.Integer(),nullable=False,server_default='2')); op.add_column('sessions',sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('session_teams',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('name',sa.String(120),nullable=False),sa.Column('sort_order',sa.Integer(),nullable=False,server_default='1'),sa.UniqueConstraint('session_id','name')); op.create_index('ix_session_teams_session_id','session_teams',['session_id'])
    op.create_table('session_participants',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('team_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('session_teams.id')),sa.Column('current_role_key',sa.String(80),server_default='team_member'),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.UniqueConstraint('session_id','person_id')); op.create_index('ix_session_participants_session_id','session_participants',['session_id'])
    op.create_table('session_role_assignments',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('role_key',sa.String(80),nullable=False),sa.Column('reason',sa.String(200)),sa.Column('assigned_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id')),sa.Column('effective_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('ended_at',sa.DateTime(timezone=True)))
    op.create_table('consent_templates',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('organization_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('organizations.id')),sa.Column('name',sa.String(200),nullable=False),sa.Column('version',sa.Integer(),nullable=False,server_default='1'),sa.Column('body',sa.Text(),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table('consent_records',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('template_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('consent_templates.id'),nullable=False),sa.Column('signer_type',sa.String(20),nullable=False),sa.Column('signer_name',sa.String(200),nullable=False),sa.Column('signer_email',sa.String(320)),sa.Column('status',sa.String(30),nullable=False,server_default='signed'),sa.Column('signed_at',sa.DateTime(timezone=True),server_default=sa.func.now()))

def downgrade():
    op.drop_table('consent_records');op.drop_table('consent_templates');op.drop_table('session_role_assignments');op.drop_table('session_participants');op.drop_table('session_teams');op.drop_column('sessions','created_at');op.drop_column('sessions','team_count');op.drop_column('sessions','status');op.drop_constraint('fk_sessions_template','sessions',type_='foreignkey');op.drop_column('sessions','template_id');op.drop_table('program_templates')
