"""v0.9 session operational workspace"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0007_session_workspace"
down_revision="0006_identity_access_consent"
branch_labels=None
depends_on=None
def upgrade():
    op.create_table('session_partner_needs',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('team_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('session_teams.id')),sa.Column('category_key',sa.String(80)),sa.Column('partner_name',sa.String(200),nullable=False),sa.Column('description',sa.Text(),nullable=False),sa.Column('priority',sa.String(20),nullable=False,server_default='normal'),sa.Column('target_quantity',sa.Float()),sa.Column('unit',sa.String(40)),sa.Column('status',sa.String(30),nullable=False,server_default='reported'),sa.Column('source_notes',sa.Text()),sa.Column('entered_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('verified_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id')),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index('ix_spn_session','session_partner_needs',['session_id']);op.create_index('ix_spn_team','session_partner_needs',['team_id'])
    op.create_table('session_contributions',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('team_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('session_teams.id')),sa.Column('category_key',sa.String(80)),sa.Column('contribution_type',sa.String(20),nullable=False),sa.Column('donor_name',sa.String(200)),sa.Column('quantity',sa.Float()),sa.Column('unit',sa.String(40)),sa.Column('weight_lbs',sa.Float()),sa.Column('amount',sa.Float()),sa.Column('designation',sa.String(200)),sa.Column('notes',sa.Text()),sa.Column('qc_status',sa.String(30),nullable=False,server_default='entered'),sa.Column('entered_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('verified_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id')),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index('ix_sc_session','session_contributions',['session_id']);op.create_index('ix_sc_team','session_contributions',['team_id'])
    op.create_table('session_outreach',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('team_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('session_teams.id')),sa.Column('contact_name',sa.String(200)),sa.Column('organization_name',sa.String(200)),sa.Column('method',sa.String(50),nullable=False,server_default='other'),sa.Column('outcome',sa.String(300)),sa.Column('follow_up_at',sa.DateTime(timezone=True)),sa.Column('notes',sa.Text()),sa.Column('entered_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index('ix_so_session','session_outreach',['session_id']);op.create_index('ix_so_team','session_outreach',['team_id'])
    op.create_table('session_activities',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('team_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('session_teams.id')),sa.Column('activity_type',sa.String(80),nullable=False),sa.Column('title',sa.String(200),nullable=False),sa.Column('description',sa.Text()),sa.Column('quantity',sa.Float()),sa.Column('entered_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index('ix_sa_session','session_activities',['session_id']);op.create_index('ix_sa_team','session_activities',['team_id'])
    op.create_table('session_handoffs',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('session_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('sessions.id'),nullable=False),sa.Column('partner_name',sa.String(200),nullable=False),sa.Column('delivered_at',sa.DateTime(timezone=True)),sa.Column('summary',sa.Text(),nullable=False),sa.Column('impact_notes',sa.Text()),sa.Column('entered_by_person_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('people.id'),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index('ix_sh_session','session_handoffs',['session_id'])
def downgrade():
    for idx,t in [('ix_sh_session','session_handoffs'),('ix_sa_team','session_activities'),('ix_sa_session','session_activities'),('ix_so_team','session_outreach'),('ix_so_session','session_outreach'),('ix_sc_team','session_contributions'),('ix_sc_session','session_contributions'),('ix_spn_team','session_partner_needs'),('ix_spn_session','session_partner_needs')]:op.drop_index(idx,table_name=t)
    for t in ['session_handoffs','session_activities','session_outreach','session_contributions','session_partner_needs']:op.drop_table(t)
