import React, {useEffect, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { Building2, Users, Boxes, CalendarDays, ChartNoAxesCombined, MessageSquare, ShieldCheck, LogOut } from 'lucide-react';
import './styles.css';

type Me={id:string,email:string,first_name:string,last_name:string,is_platform_admin:boolean};
const nav = [['Organizations',Building2],['People',Users],['Programs & Simulations',Boxes],['Sessions',CalendarDays],['Leadership Development',ChartNoAxesCombined],['Communications',MessageSquare],['Administration',ShieldCheck]] as const;

function Login({onLogin}:{onLogin:(t:string)=>void}){
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Login failed');localStorage.setItem('ali_token',d.access_token);onLogin(d.access_token);}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="loginPage"><form className="loginCard" onSubmit={submit}><div className="brand loginBrand"><div className="mark">ALI</div><div><strong>ALI SIMULATIONS</strong><span>Leadership, Experienced.</span></div></div><h1>Sign in</h1><p>Secure access to the ALI Simulations development environment.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button><small>v0.2 · Authentication foundation</small></form></div>
}
function App(){const [token,setToken]=useState(localStorage.getItem('ali_token')||'');const [me,setMe]=useState<Me|null>(null);useEffect(()=>{if(!token)return;fetch('/api/auth/me',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(!r.ok)throw 0;return r.json()}).then(setMe).catch(()=>{localStorage.removeItem('ali_token');setToken('')})},[token]);if(!token)return <Login onLogin={setToken}/>;if(!me)return <div className="loading">Loading ALI Simulations…</div>;function logout(){localStorage.removeItem('ali_token');setToken('');setMe(null)}return <div className="shell"><aside><div className="brand"><div className="mark">ALI</div><div><strong>ALI SIMULATIONS</strong><span>Leadership, Experienced.</span></div></div><nav>{nav.map(([label,Icon],i)=><button className={i===0?'active':''} key={label}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={17}/>Sign out</button><div className="footer">Development foundation · v0.2</div></aside><main><header><div><span className="eyebrow">{me.is_platform_admin?'PLATFORM ADMINISTRATOR':'AUTHORIZED USER'}</span><h1>Platform Dashboard</h1></div><div className="avatar">{me.first_name[0]}{me.last_name[0]}</div></header><section className="hero"><div><span className="eyebrow">WELCOME, {me.first_name.toUpperCase()}</span><h2>Authentication is live.</h2><p>v0.2 connects the React interface to FastAPI and PostgreSQL, seeds the permission catalog, and creates the first secure Platform Administrator account from Render environment variables.</p></div><div className="status"><span>V0.2</span><strong>Auth + Core DB</strong><small>React · FastAPI · PostgreSQL</small></div></section><section className="cards"><Card n="1" t="Authenticated User" s={me.email}/><Card n="8" t="Core Roles" s="Permission-backed access model"/><Card n="21" t="Permissions" s="Seeded capability catalog"/><Card n="ON" t="Database Health" s="Verified on API health check"/></section><section className="panel"><div><span className="eyebrow">NEXT BUILD</span><h3>People, organizations & licensing administration</h3></div><div className="flow"><b>People</b><span>→</span><b>Organizations</b><span>→</span><b>Memberships</b><span>→</span><b>Simulation Entitlements</b><span>→</span><b>Audit</b></div></section></main></div>}
function Card({n,t,s}:{n:string,t:string,s:string}){return <article><strong>{n}</strong><h3>{t}</h3><p>{s}</p></article>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
